// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWMKSn2JghbAWtHxXUnJisFXaorn1mxyo',
    appId: '1:662769253670:web:00b557d1d7608f559595e7',
    messagingSenderId: '662769253670',
    projectId: 'gradproject-9e39e',
    authDomain: 'gradproject-9e39e.firebaseapp.com',
    storageBucket: 'gradproject-9e39e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxHPc3Ge46ba3l3R2uaDISdFXPKOkfyHs',
    appId: '1:662769253670:android:6dd6dac38f6b0f789595e7',
    messagingSenderId: '662769253670',
    projectId: 'gradproject-9e39e',
    storageBucket: 'gradproject-9e39e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBotPQWDIOFURDMFeeS7RUsCSBcWaK5P1c',
    appId: '1:662769253670:ios:152c1c7fd60177099595e7',
    messagingSenderId: '662769253670',
    projectId: 'gradproject-9e39e',
    storageBucket: 'gradproject-9e39e.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBotPQWDIOFURDMFeeS7RUsCSBcWaK5P1c',
    appId: '1:662769253670:ios:152c1c7fd60177099595e7',
    messagingSenderId: '662769253670',
    projectId: 'gradproject-9e39e',
    storageBucket: 'gradproject-9e39e.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWMKSn2JghbAWtHxXUnJisFXaorn1mxyo',
    appId: '1:662769253670:web:86854809d835fa559595e7',
    messagingSenderId: '662769253670',
    projectId: 'gradproject-9e39e',
    authDomain: 'gradproject-9e39e.firebaseapp.com',
    storageBucket: 'gradproject-9e39e.firebasestorage.app',
  );
}
